vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|30 Apr 2009 15:36:23 -0000
vti_extenderversion:SR|5.0.2.2623
vti_cacheddtm:TX|30 Apr 2009 15:36:23 -0000
vti_filesize:IR|11526
vti_cachedtitle:SR|:::: HARAS LUANDA ::::
vti_cachedbodystyle:SR|<body leftmargin="0" topmargin="0">
vti_cachedlinkinfo:VX|Q|estilo.css S|Scripts/AC_RunActiveContent.js S|Scripts/lightbox.js Q|css/lightbox.css D|clsid:D27CDB6E-AE6D-11cf-96B8-444553540000 D|http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab S|swf/menu.swf D|clsid:D27CDB6E-AE6D-11cf-96B8-444553540000 D|http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab S|swf/topo.swf S|images/shim.gif S|images/shim.gif S|images/shim.gif H|images/potroas/01.jpg S|images/potroas/01_pq.jpg H|images/potroas/02.jpg S|images/potroas/02_pq.jpg H|images/potroas/03.jpg S|images/potroas/03_pq.jpg H|images/potroas/04.jpg S|images/potroas/04_pq.jpg H|images/potroas/05.jpg S|images/potroas/05_pq.jpg S|images/shim.gif S|images/tit_potroas.gif S|images/shim.gif S|images/shim.gif S|images/shim.gif S|images/shim.gif H|images/potroas/01.jpg H|images/potroas/02.jpg H|images/potroas/03.jpg H|images/potroas/04.jpg H|images/potroas/05.jpg H|images/potroas/06.jpg H|images/potroas/07.jpg H|images/potroas/08.jpg H|images/potroas/09.jpg H|images/potroas/10.jpg H|images/potroas/11.jpg H|images/potroas/12.jpg H|images/potroas/13.jpg H|images/potroas/14.jpg H|images/potroas/15.jpg H|images/potroas/16.jpg H|images/potroas/17.jpg H|images/potroas/18.jpg H|images/potroas/19.jpg H|images/potroas/20.jpg H|images/potroas/21.jpg S|images/home_topo.gif K|potroas.asp
vti_cachedsvcrellinks:VX|FQUS|antigo/estilo.css FSUS|antigo/Scripts/AC_RunActiveContent.js FSUS|antigo/Scripts/lightbox.js FQUS|antigo/css/lightbox.css NDUS|clsid:D27CDB6E-AE6D-11cf-96B8-444553540000 NDHS|http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab FSUS|antigo/swf/menu.swf NDUS|clsid:D27CDB6E-AE6D-11cf-96B8-444553540000 NDHS|http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab FSUS|antigo/swf/topo.swf FSUS|antigo/images/shim.gif FSUS|antigo/images/shim.gif FSUS|antigo/images/shim.gif FHUS|antigo/images/potroas/01.jpg FSUS|antigo/images/potroas/01_pq.jpg FHUS|antigo/images/potroas/02.jpg FSUS|antigo/images/potroas/02_pq.jpg FHUS|antigo/images/potroas/03.jpg FSUS|antigo/images/potroas/03_pq.jpg FHUS|antigo/images/potroas/04.jpg FSUS|antigo/images/potroas/04_pq.jpg FHUS|antigo/images/potroas/05.jpg FSUS|antigo/images/potroas/05_pq.jpg FSUS|antigo/images/shim.gif FSUS|antigo/images/tit_potroas.gif FSUS|antigo/images/shim.gif FSUS|antigo/images/shim.gif FSUS|antigo/images/shim.gif FSUS|antigo/images/shim.gif FHUS|antigo/images/potroas/01.jpg FHUS|antigo/images/potroas/02.jpg FHUS|antigo/images/potroas/03.jpg FHUS|antigo/images/potroas/04.jpg FHUS|antigo/images/potroas/05.jpg FHUS|antigo/images/potroas/06.jpg FHUS|antigo/images/potroas/07.jpg FHUS|antigo/images/potroas/08.jpg FHUS|antigo/images/potroas/09.jpg FHUS|antigo/images/potroas/10.jpg FHUS|antigo/images/potroas/11.jpg FHUS|antigo/images/potroas/12.jpg FHUS|antigo/images/potroas/13.jpg FHUS|antigo/images/potroas/14.jpg FHUS|antigo/images/potroas/15.jpg FHUS|antigo/images/potroas/16.jpg FHUS|antigo/images/potroas/17.jpg FHUS|antigo/images/potroas/18.jpg FHUS|antigo/images/potroas/19.jpg FHUS|antigo/images/potroas/20.jpg FHUS|antigo/images/potroas/21.jpg FSUS|antigo/images/home_topo.gif FKUS|antigo/potroas.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1
vti_charset:SR|windows-1252
vti_title:SR|:::: HARAS LUANDA ::::
vti_backlinkinfo:VX|antigo/inc_base.asp antigo/potroas.asp
